// To parse this JSON data, do
//
//     final leadNameModel = leadNameModelFromJson(jsonString);

import 'dart:convert';

LeadNameModel leadNameModelFromJson(String str) => LeadNameModel.fromJson(json.decode(str));

String leadNameModelToJson(LeadNameModel data) => json.encode(data.toJson());

class LeadNameModel {
    String name;
   dynamic  creation;
    dynamic modified;
    String modifiedBy;
    String owner;
    dynamic docstatus;
    dynamic idx;
    String namingSeries;
    dynamic salutation;
    String firstName;
    dynamic middleName;
    dynamic lastName;
    String leadName;
    dynamic jobTitle;
    dynamic gender;
    dynamic source;
    String leadOwner;
    String status;
    dynamic customer;
    String type;
    String requestType;
    dynamic emailId;
    dynamic website;
    String mobileNo;
    dynamic whatsappNo;
    dynamic phone;
    dynamic phoneExt;
    dynamic companyName;
    String noOfEmployees;
    dynamic annualRevenue;
    dynamic industry;
    dynamic marketSegment;
    dynamic territory;
    dynamic fax;
    dynamic city;
    dynamic state;
    String country;
    String qualificationStatus;
    dynamic qualifiedBy;
    dynamic qualifiedOn;
    dynamic campaignName;
    String company;
    String language;
    dynamic image;
    String title;
    dynamic disabled;
    dynamic unsubscribed;
    dynamic blogSubscriber;
    dynamic userTags;
    dynamic comments;
    dynamic assign;
    dynamic likedBy;

    LeadNameModel({
        required this.name,
        required this.creation,
        required this.modified,
        required this.modifiedBy,
        required this.owner,
        required this.docstatus,
        required this.idx,
        required this.namingSeries,
        required this.salutation,
        required this.firstName,
        required this.middleName,
        required this.lastName,
        required this.leadName,
        required this.jobTitle,
        required this.gender,
        required this.source,
        required this.leadOwner,
        required this.status,
        required this.customer,
        required this.type,
        required this.requestType,
        required this.emailId,
        required this.website,
        required this.mobileNo,
        required this.whatsappNo,
        required this.phone,
        required this.phoneExt,
        required this.companyName,
        required this.noOfEmployees,
        required this.annualRevenue,
        required this.industry,
        required this.marketSegment,
        required this.territory,
        required this.fax,
        required this.city,
        required this.state,
        required this.country,
        required this.qualificationStatus,
        required this.qualifiedBy,
        required this.qualifiedOn,
        required this.campaignName,
        required this.company,
        required this.language,
        required this.image,
        required this.title,
        required this.disabled,
        required this.unsubscribed,
        required this.blogSubscriber,
        required this.userTags,
        required this.comments,
        required this.assign,
        required this.likedBy,
    });

    factory LeadNameModel.fromJson(Map<String, dynamic> json) => LeadNameModel(
        name: json["name"]??"",
        creation: (json["creation"]??""),
        modified: (json["modified"]??""),
        modifiedBy: json["modified_by"]??"",
        owner: json["owner"]??"",
        docstatus: json["docstatus"]??"",
        idx: json["idx"]??"",
        namingSeries: json["naming_series"]??"",
        salutation: json["salutation"]??"",
        firstName: json["first_name"]??"",
        middleName: json["middle_name"]??"",
        lastName: json["last_name"]??"",
        leadName: json["lead_name"]??"",
        jobTitle: json["job_title"]??"",
        gender: json["gender"]??"",
        source: json["source"]??"",
        leadOwner: json["lead_owner"]??"",
        status: json["status"]??"",
        customer: json["customer"]??"",
        type: json["type"]??"",
        requestType: json["request_type"]??"",
        emailId: json["email_id"]??"",
        website: json["website"]??"",
        mobileNo: json["mobile_no"]??"",
        whatsappNo: json["whatsapp_no"]??"",
        phone: json["phone"]??"",
        phoneExt: json["phone_ext"]??"",
        companyName: json["company_name"]??"",
        noOfEmployees: json["no_of_employees"]??"",
        annualRevenue: json["annual_revenue"]??"",
        industry: json["industry"]??"",
        marketSegment: json["market_segment"]??"",
        territory: json["territory"]??"",
        fax: json["fax"]??"",
        city: json["city"]??"",
        state: json["state"]??"",
        country: json["country"]??"",
        qualificationStatus: json["qualification_status"]??"",
        qualifiedBy: json["qualified_by"]??"",
        qualifiedOn: json["qualified_on"]??"",
        campaignName: json["campaign_name"]??"",
        company: json["company"]??"",
        language: json["language"]??"",
        image: json["image"]??"",
        title: json["title"]??"",
        disabled: json["disabled"]??"",
        unsubscribed: json["unsubscribed"]??"",
        blogSubscriber: json["blog_subscriber"]??"",
        userTags: json["_user_tags"]??"",
        comments: json["_comments"]??"",
        assign: json["_assign"]??"",
        likedBy: json["_liked_by"]??"",
    );

    Map<String, dynamic> toJson() => {
        "name": name,
        "creation": creation.toIso8601String(),
        "modified": modified.toIso8601String(),
        "modified_by": modifiedBy,
        "owner": owner,
        "docstatus": docstatus,
        "idx": idx,
        "naming_series": namingSeries,
        "salutation": salutation,
        "first_name": firstName,
        "middle_name": middleName,
        "last_name": lastName,
        "lead_name": leadName,
        "job_title": jobTitle,
        "gender": gender,
        "source": source,
        "lead_owner": leadOwner,
        "status": status,
        "customer": customer,
        "type": type,
        "request_type": requestType,
        "email_id": emailId,
        "website": website,
        "mobile_no": mobileNo,
        "whatsapp_no": whatsappNo,
        "phone": phone,
        "phone_ext": phoneExt,
        "company_name": companyName,
        "no_of_employees": noOfEmployees,
        "annual_revenue": annualRevenue,
        "industry": industry,
        "market_segment": marketSegment,
        "territory": territory,
        "fax": fax,
        "city": city,
        "state": state,
        "country": country,
        "qualification_status": qualificationStatus,
        "qualified_by": qualifiedBy,
        "qualified_on": qualifiedOn,
        "campaign_name": campaignName,
        "company": company,
        "language": language,
        "image": image,
        "title": title,
        "disabled": disabled,
        "unsubscribed": unsubscribed,
        "blog_subscriber": blogSubscriber,
        "_user_tags": userTags,
        "_comments": comments,
        "_assign": assign,
        "_liked_by": likedBy,
    };
}
